version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile-test
    environment:
      NODE_ENV: test
      KEYCLOAK_TEST_CLIENT_NAME: test
      KEYCLOAK_TEST_CLIENT_SECRET: 9067b642-015a-441a-816b-0c8d19305d10
    ports:
      - 8888:8888
    volumes:
      - './coverage:/app/coverage'
      - './mochawesome-report:/app/mochawesome-report'
      - './report:/app/report'
    depends_on:
      - keycloak

  # --------------- #
  #     KEYCLOAK    #
  # --------------- #
  keycloak:
    image: jboss/keycloak:8.0.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
      KEYCLOAK_LOGLEVEL: debug
    ports:
      - 8080:8080
