FROM node:lts-alpine as build

WORKDIR /build
COPY package.json package.json
COPY yarn.lock yarn.lock
RUN yarn 

COPY . .
RUN yarn build 

FROM fireblink/fbl-plugins:1.0.89

WORKDIR /app

COPY --from=build /build/node_modules node_modules
COPY --from=build /build/dist dist
COPY --from=build /build/config config
COPY --from=build /build/package.json .
COPY --from=build /build/test test
COPY --from=build /build/src src
COPY --from=build /build/test.sh .
COPY --from=build /build/tsconfig.json .
COPY --from=build /build/.mocharc.yml .

CMD ["sh", "test.sh"]

