version: 2

jobs:  
  build:
    working_directory: ~/workspace
    machine: true
    steps:         
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - checkout

      - run: 
          name: Run tests
          command: |
            docker-compose up --build --abort-on-container-exit
            

      # generate coverage report
      - run: ./node_modules/.bin/nyc report --reporter=text-lcov > ./coverage.lcov

      # send test coverage
      - run: bash <(curl -s https://codecov.io/bash) -f ./coverage.lcov