# the client id for the 'client' application
port: APP_PORT
interface: APP_INTERFACE
host: APP_HOST

log:
  level: APP_LOG_LEVEL

keycloak:
  clients:
    __name: APP_KEYCLOAK_CLIENTS
    __format: json

  scopes:
    __name: APP_KEYCLOAK_SCOPES
    __format: json

upstreamURL: APP_UPSTREAM_URL

paths:
  callback: APP_PATHS_CALLBACK
  logout: APP_PATHS_LOGOUT
  health: APP_PATHS_HEALTH

logoutRedirectURL: APP_LOGOUT_REDIRECT_URL

headers:
  __name: APP_HEADERS
  __format: json

cookie:
  secure: APP_COOKIE_SECURE
  accessToken: APP_COOKIE_ACCESS_TOKEN
  refreshToken: APP_COOKIE_REFRESH_TOKEN

jwtVerification: APP_JWT_VERIFICATION_MODE

resources:
  __name: APP_RESOURCES
  __format: json

