# Port to listen for incoming connections
port: 3000
# Interface to listen
interface: 127.0.0.1
# Public facing hostname
host: http://127.0.0.1:3000

log:
  level: info

keycloak:
  # client_id/secret pairs of supported KC clients
  clients:
      - clientId: <CLIENT_ID>
        secret: <CLIENT_SECRET>
        realmURL:
          public: https://keycloak.example.com/auth/realms/<REALM_NAME>
          private: http://keycloak.local:8080/auth/realms/<REALM_NAME>

    # additional scopes to add to add to the default (openid+email+profile)
  scopes: []

# the upstream endpoint which we should proxy request
upstreamURL: http://127.0.0.1:80

# Extra URL handlers paths
paths:
  # OID callback path
  callback: /oauth/callback
  # User logout path
  logout: /logout
  # Application healthcheck endpoint
  health: /healthz

# Redirect URL to be used upon logout
logoutRedirectURL: /

headers: {}

cookie:
  secure: '1'
  accessToken: kc-access-token
  refreshToken: kc-refresh-token

# a collection of resource i.e. urls that you wish to protect
resources: []

jwtVerification: OFFLINE # or ONLINE






